### ISSUE TITLE
Resulting rom crashes, possible dump issue.

### ISSUE THREAD

**Issue by HGwells628** [Prof9/mmzc-full-screen#1]
After setting up the program as instructed, the resulting rom was unable to launch on my system. Given posts on the Rockmanexezone forum, I suspect this is a result of a mis-matched dump from the one intended. However the lack of checksum information makes this impossible to verify, and the dump mentioned on the site no longer appears to be available in any case. The only one that is to be found has a CRC32 of `4CC19A32`. A bps patch, like the one provided for the ZX Slot 2 patch, would also be nice if it's possible.

**Comment by HGwells628** [comment]
I stand corrected, I was attempting to play on a real hardware using an R4 device, which was applying an AP patch without my knowing. The patched rom does not get this same benefit because of its altered checksum. It does work correctly in an emulator, however.

**Comment by Prof9** [comment]
If you're talking about [this](https://forums.therockmanexezone.com/mega-man-zero-collection-screen-mod-t2827.html), that's a pretty old version of the mod. The one in this repo uses a clean ROM, i.e. one that you dump from your own cartridge.

This mod is _far_ from complete and I doubt I'll get around to finishing it anytime soon, so a BPS patch is not planned for the time being.
